apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  # creationTimestamp: "2022-07-30T11:28:31Z"
  generation: 1
  labels:
    app: restaurant
  name: restaurant
  namespace: default
  # resourceVersion: "2026"
  # uid: 0dc2b867-09be-4413-abfa-da1ca2fdc9c2
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: restaurant
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      # creationTimestamp: null
      labels:
        app: restaurant
    spec:
      containers:
      - image: restaurant
        imagePullPolicy: IfNotPresent
        name: echoserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-30T11:28:47Z"
    lastUpdateTime: "2022-07-30T11:28:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-07-30T11:28:31Z"
    lastUpdateTime: "2022-07-30T11:28:47Z"
    message: ReplicaSet "restaurant-5c5f5cddb9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1