apiVersion: v1
kind: Service
metadata:
  name: restaurant
  labels:
    app: restaurant
spec:
  type: NodePort
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000