# Generated by Django 2.2.12 on 2022-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220624_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
