# Generated by Django 2.2.12 on 2022-06-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220624_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secret_key',
        ),
    ]
