# Generated by Django 2.2.12 on 2022-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_user_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
