# Generated by Django 2.2.12 on 2022-06-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_password_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
