# Generated by Django 2.2.12 on 2022-06-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_user_otp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_time',
            new_name='password_reset_otp_time',
        ),
    ]
