# Generated by Django 2.2.12 on 2022-06-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220627_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customerid',
            new_name='customerId',
        ),
    ]
