# Generated by Django 2.2.12 on 2022-06-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220628_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='customerId',
            new_name='customerid',
        ),
    ]
