# Generated by Django 2.2.12 on 2022-06-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20220629_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='producer_name',
            new_name='name',
        ),
    ]
