# Generated by Django 2.2.12 on 2022-06-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20220629_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producer',
            old_name='name',
            new_name='namee',
        ),
    ]
