# Generated by Django 2.2.12 on 2022-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20220629_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product_price',
            field=models.CharField(max_length=100),
        ),
    ]
