# Generated by Django 2.2.12 on 2022-06-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20220629_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
