# Generated by Django 2.2.12 on 2022-06-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20220630_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='idd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.User'),
            preserve_default=False,
        ),
    ]
