# Generated by Django 2.2.12 on 2022-06-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_customer_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='idd',
            new_name='cid',
        ),
    ]
