# Generated by Django 2.2.12 on 2022-06-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20220630_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cid',
        ),
    ]
