# Generated by Django 2.2.12 on 2022-06-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_customer_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='idd',
        ),
    ]
